-- MySQL Script generated by MySQL Workbench
-- 04/27/16 08:22:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemahotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemahotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemahotel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sistemahotel` ;

-- -----------------------------------------------------
-- Table `sistemahotel`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemahotel`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `RFC` VARCHAR(30) NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL COMMENT '',
  `Direccion` VARCHAR(45) NOT NULL COMMENT '',
  `Telefono` INT NOT NULL COMMENT '',
  `Correo_electronico` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_cliente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemahotel`.`Habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemahotel`.`Habitaciones` (
  `idHabitaciones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Numero_habitacion` VARCHAR(5) NOT NULL COMMENT '',
  `Piso` VARCHAR(3) NOT NULL COMMENT '',
  `Descripcion` VARCHAR(60) NULL COMMENT '',
  `Caracteristicas` VARCHAR(60) NULL COMMENT '',
  `Precio` VARCHAR(10) NOT NULL COMMENT '',
  `Estado` VARCHAR(20) NOT NULL COMMENT '',
  `Tipo_habitacion` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idHabitaciones`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemahotel`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemahotel`.`Usuario` (
  `id_cliente` INT NOT NULL COMMENT '',
  `Password` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id_cliente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemahotel`.`Reservaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemahotel`.`Reservaciones` (
  `idReservaciones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Tipo_reserva` VARCHAR(20) NOT NULL COMMENT '',
  `Fecha_reserva` DATE NOT NULL COMMENT '',
  `Fecha_entrada` DATE NOT NULL COMMENT '',
  `Fecha_salida` DATE NOT NULL COMMENT '',
  `Costo` VARCHAR(10) NOT NULL COMMENT '',
  `Observaciones` VARCHAR(45) NOT NULL COMMENT '',
  `Estado` VARCHAR(15) NOT NULL COMMENT '',
  `idHabitaciones` INT NOT NULL COMMENT '',
  `idcliente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idReservaciones`)  COMMENT '',
  INDEX `fk_Reservaciones_Habitaciones1_idx` (`idHabitaciones` ASC)  COMMENT '',
  INDEX `fk_Reservaciones_Clientes1_idx` (`idcliente` ASC)  COMMENT '',
  CONSTRAINT `fk_Reservaciones_Habitaciones1`
    FOREIGN KEY (`idHabitaciones`)
    REFERENCES `sistemahotel`.`Habitaciones` (`idHabitaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservaciones_Clientes1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `sistemahotel`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemahotel`.`Promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemahotel`.`Promociones` (
  `idPromociones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Paquetes` VARCHAR(45) NOT NULL COMMENT '',
  `Precio_venta` VARCHAR(10) NOT NULL COMMENT '',
  `Descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `idReservaciones` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPromociones`)  COMMENT '',
  INDEX `fk_Promociones_Reservaciones1_idx` (`idReservaciones` ASC)  COMMENT '',
  CONSTRAINT `fk_Promociones_Reservaciones1`
    FOREIGN KEY (`idReservaciones`)
    REFERENCES `sistemahotel`.`Reservaciones` (`idReservaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemahotel`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemahotel`.`Factura` (
  `Folio_fiscal` VARCHAR(45) NOT NULL COMMENT '',
  `Fecha_emision` DATE NOT NULL COMMENT '',
  `Hora_inicial` TIME(6) NOT NULL COMMENT '',
  `Hora_final` TIME(6) NOT NULL COMMENT '',
  `RFC_emisor` VARCHAR(45) NOT NULL COMMENT '',
  `Estado_comprobante` VARCHAR(45) NOT NULL COMMENT '',
  `idcliente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Folio_fiscal`)  COMMENT '',
  INDEX `fk_Factura_Clientes1_idx` (`idcliente` ASC)  COMMENT '',
  CONSTRAINT `fk_Factura_Clientes1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `sistemahotel`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
